apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: app-deploy
---
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pvc
  namespace: default
  labels:
    app: app-deploy
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-deploy
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app-deploy
    spec:
      containers:
      - env:
        - name: APP_DB_HOST
          value: app-mysql
        - name: APP_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mysql-pass
        image: tawdeb/php5-build:1.0.0
        imagePullPolicy: Always
        name: php5-deploy
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        volumeMounts:
        - mountPath: /var/www/html
          name: forodata
        - mountPath: /usr/local/etc/php/conf.d/custom.ini
          name: config-volume
          subPath: custom.ini
      volumes:
      - name: forodata
        persistentVolumeClaim:
          claimName: app-pvc
      - configMap:
          defaultMode: 420
          name: custom-ini
        name: config-volume
